### PR TITLE
benchmark/nixlbench: Fixes #1152 - GUSLI auto-generated conf

### LINKED ISSUE #1152: nixlbench: Incorrect generated GUSLI config file
in nixl_worker.cpp:
generateGusliConfigFile() generates config file in the format:
```
        // Format: "id type access_mode shared_exclusive path security_flags"
        // Example: "11 F W N ./store0.bin sec=0x3"

```
argument #4 is "shared exclusive" while gusli config parser expects "direct i/o"

gusli config parser expects arg[3] to be 'D' or 'd' - direct i/o
in gusli code client_imp.cpp:
```
   bdev_config_params::init_parse() 
      n_args_read += sscanf(argv[3], "%c", &c); is_direct_io = (bool)((c == 'D')||(c == 'd'));

```

proposal fix:

```
diff --git a/benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp b/benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
index 5068a6d..5fa9d7a 100644
--- a/benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
+++ b/benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
@@ -79,10 +79,10 @@ generateGusliConfigFile(const std::vector<GusliDeviceConfig> &devices) {
     config << "# Config file\nversion=1\n";

     for (const auto &dev : devices) {
-        // Format: "id type access_mode shared_exclusive path security_flags"
-        // Example: "11 F W N ./store0.bin sec=0x3"
+        // Format: "id type access_mode direct_io path security_flags"
+        // Example: "11 F W D ./store0.bin sec=0x3"
         config << dev.device_id << " " << dev.device_type << " "
-               << "W N " // Write mode, Not shared (exclusive)
+               << "W D " // Write mode, Direct I/O
                << dev.device_path << " " << dev.security_flags << "\n";
     }

```

### PR DESCRIPTION
**Pull request by omer-b1**
Fix incorrect auto-generated GUSLI config file

### CODE REVIEW

File: benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
+ * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
```
Comment (aranadive) [inline benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp]: Should be 2025-2026
